[package]
name = "so-proj-client"
version = "0.1.0"
authors = ["0Phineas0 <phineas.guifontes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "4.0"
num_enum = "0.4.2"
